### Site info:
title: Tu Android
tagline: Blog de Android
title: "Blog Tu Android"
description: "Blog dedicado a informar sobre las últimas novedades del mundo Android y a los mejores Smartphones"
keywords: "android, smartphone, móviles"

url: "http://tuandroid.es" # the base hostname & protocol for your site

l




 # Scripts

analytics :
  provider : google 
  google : 
      tracking_id : ''


### Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5


exclude: ['README.md', 'LICENSE']
